import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  zh: {
    'nav.workflow': '工作流引擎',
    'nav.features': '核心特性',
    'nav.architecture': '工业架构',
    'nav.capabilities': '深度能力',
    'nav.alignment': '安全对齐',
    'nav.vision': '生态愿景',
    'nav.pricing': '价格方案',
    'nav.login': '登录',
    'nav.start': '立即开始',
    'hero.badge': '基础设施 2.0 现已发布',
    'hero.title': 'IntelliFlow：专为文件数据处理与工作流自动化打造',
    'hero.desc': '工业级基础设施，让复杂的自动化 DAG 流水线触手可及。',
    'hero.start': '开始构建',
    'hero.docs': '查看文档',
    'hero.node1': 'Excel 读取器',
    'hero.node2': 'AI 模型引擎',
    'hero.node3': 'WebHook 触发',
    'features.dag.title': '无代码 DAG 编辑器',
    'features.dag.desc': '拖拽式界面，支持数千个逻辑节点的无缝连接与实时数据预览。',
    'features.latency.title': '毫秒级延迟',
    'features.latency.desc': '专为高并发工业场景设计的执行内核，确保流水线在边缘侧极速运行。',
    'features.encryption.title': '端到端加密',
    'features.encryption.desc': '所有敏感数据均在本地环境以及云端加密环境完成处理，不留任何痕迹。',
    'features.integration.title': '深度模型集成',
    'features.integration.desc': '原生支持私有部署的行业级 LLM。',
    'features.telemetry.title': '实时遥测',
    'features.telemetry.desc': '精确监控每一个节点的资源占用情况与执行链路分析。',
    'flow.node1': '数据接入',
    'flow.node2': '大模型处理',
    'flow.node3': '结果生成',
    'flow.title': '可视化 DAG 编排',
    'flow.desc': '通过直观的拖拽界面设计复杂工作流。无缝连接异构模型与数据源。',
    'safety.core.title': '工业级安全核心',
    'safety.core.desc': '我们的内核级拦截机制在提示词到达API之前，就防止LLM执行危险命令或违反公司合规政策。',
    'safety.redteam.title': '自动化红蓝对抗',
    'safety.redteam.desc': '持续的对抗性测试在部署前识别特定模型实现中的漏洞。',
    'safety.reliability.title': '运行可靠性',
    'safety.compliance.title': '合规就绪',
    'visual.label': 'Industrial Core',
    'visual.title1': '为复杂性而生',
    'visual.title2': '而不被复杂性困扰',
    'visual.desc': '在 IntelliFlow 出现之前，构建跨系统的数据流意味着无休止的代码调试。现在，我们将其抽象为直观的可视化原子节点，让非技术人员也能参与到企业级基础设施的构建中。',
    'visual.feature1.title': '弹性扩展架构',
    'visual.feature1.desc': '支持从单一任务到集群级别的自动平滑扩容。',
    'visual.feature2.title': '版本回溯系统',
    'visual.feature2.desc': '完整的 Git 风格工作流版本管理，随时恢复至任一历史状态。',
    'capabilities.badge': '核心能力 2.0',
    'capabilities.title1': '工程化',
    'capabilities.title2': '工业级',
    'capabilities.title3': '智能。',
    'capabilities.desc': '体验下一代流程自动化。我们的三层架构将逆向工程与异构执行相结合，实现手术级的精准度。',
    'capabilities.mod1.label': '模块 01 // 智能分析',
    'capabilities.mod1.title': '少样本逆向推导',
    'capabilities.mod1.desc1': '告别冗长的硬编码与规则穷举。IntelliFlow 首创原生',
    'capabilities.mod1.desc2': '“师徒带教模式”',
    'capabilities.mod1.desc3': '，用户只需提供“原始文件+提示词意图+目标结果”的三元组，底层算法即可瞬间“顿悟”，逆向拆解出数据提取、级别判定等中间推理步骤，一键生成可视化的有向无环图（DAG）工作流。',
    'capabilities.mod1.box.title': '师徒带教逻辑',
    'capabilities.mod1.box.desc': '“导师”级 AI 实时观察专家交互，提取高维逻辑模式，同时“学徒”脚本引擎同步生成优化的执行路径。',
    'capabilities.mod1.list1': '零延迟模式识别',
    'capabilities.mod1.list2': '自动过滤用户行为噪声',
    'capabilities.mod1.stat.label': '映射状态',
    'capabilities.mod1.stat.value': '98.4% 准确率',
    'capabilities.mod2.label': '模块 02 // 高效执行',
    'capabilities.mod2.title': '异构节点双模驱动',
    'capabilities.mod2.desc1': '杀鸡焉用牛刀。我们将传统确定性算法（如正则匹配、Python 脚本）与非确定性 AI 语义理解深度融合。在 IntelliFlow 中，大模型不再包揽一切，而是仅负责最核心的',
    'capabilities.mod2.desc2': '逻辑推理（约占 45%）',
    'capabilities.mod2.desc3': '，剩余',
    'capabilities.mod2.desc4': '55% 的数据清洗任务',
    'capabilities.mod2.desc5': '交由低成本的本地算子完成，实现算力与准确率的极致优化。',
    'capabilities.mod2.stat1.label': '认知 AI',
    'capabilities.mod2.stat1.desc': '处理边界情况与动态决策门控。',
    'capabilities.mod2.stat2.label': '本地脚本',
    'capabilities.mod2.stat2.desc': '高速、低资源消耗的二进制执行。',
    'capabilities.mod2.quote': '“通过将重复性任务卸载到优化的本地脚本，我们在保持 AI 灵活性的同时，将服务器开销降低了 64%。”',
    'capabilities.mod2.img.label1': '活动混合模式',
    'capabilities.mod2.img.label2': '节点: 0X-F42',
    'capabilities.mod3.label': '模块 03 // 规模扩展',
    'capabilities.mod3.title': '大规模并发与自动化路由',
    'capabilities.mod3.desc1': '专为企业级吞吐量设计。无论是数百份格式各异的奖学金证明 PDF，还是复杂的业务发票，自动化批量中心均能提供高速并发执行与队列监控。结合',
    'capabilities.mod3.desc2': '动态路由分发机制',
    'capabilities.mod3.desc3': '，智能调度最适合当前节点的闭源大模型 API。',
    'capabilities.mod3.chart.label1': '全局流转速率',
    'capabilities.mod3.chart.label2': '实时指标',
    'capabilities.cta.title': '准备好优化您的流程了吗？',
    'capabilities.cta.desc': '使用我们预置的工业连接器，部署时间不到 15 分钟。保证零停机集成。',
    'capabilities.cta.btn': '申请原型试用',
    'capabilities.cta.sla.label': '运行时间 SLA',
    'capabilities.cta.sla.desc': '跨 14 个全球区域的冗余路由确保您的自动化永不离线。',
    'alignment.badge': '系统完整性协议',
    'alignment.title1': '驯服',
    'alignment.title2': 'LLM',
    'alignment.desc': 'LLM不再主导您的输出。IntelliFlow 引入了多层工业级底座，旨在拦截幻觉并将非确定性推理与业务现实对齐。',
    'alignment.btn': '查看安全标准',
    'alignment.stat1.label': 'TOKEN_ENTROPY (Token熵)',
    'alignment.stat2.label': 'ALIGNMENT_SCORE (对齐分)',
    'alignment.mod1.label': '模块 01 // 幻觉压制',
    'alignment.mod1.title': '攻克注意力丢失，从物理层面压制幻觉',
    'alignment.mod1.desc': '当模型一次性吞咽海量图文时，极易产生‘中间注意力丢失’（Lost in the Middle）与数据捏造。IntelliFlow 采用分而治之的策略，通过DAG 工作流将全局任务强制解耦为原子化的节点任务。每个节点仅获取最小必要上下文，‘AI 负责模糊认知，代码负责精确执行’，将模型的动作空间极致收敛，从根本上杜绝业务幻觉。',
    'alignment.mod1.card1.title': '节点隔离',
    'alignment.mod1.card1.desc': '每个逻辑步骤都在无菌计算环境中处理，剔除无关的上下文噪声。',
    'alignment.mod1.card2.title': '交叉比对验证',
    'alignment.mod1.card2.desc': '输出结果自动与内部知识图谱进行验证，实时标记不一致之处。',
    'alignment.mod1.card3.title': '置信度闸门',
    'alignment.mod1.card3.desc': '低于特定熵阈值的Token将被锁定，并重定向至递归采样或人工审计。',
    'alignment.mod2.label': '模块 02 // 人机协同',
    'alignment.mod2.title': '思维链可视化与定点干预',
    'alignment.mod2.desc': '我们将大模型隐秘的‘思维链’外化为前端可交互的节点连线图。如果AI 在某个微观节点（如比赛定级）出现误判，人类可以直接在该节点进行定点拦截与重构。通过设定‘置信度闸门’，低置信度任务自动打入异常池转交人工复核，真正实现‘AI 负责干苦力，人类负责踩刹车’的0 误差系统底线。',
    'alignment.mod2.list1.title': '视觉透明化',
    'alignment.mod2.list1.desc': '模型内心独白的实时流，格式化以供工业审计。',
    'alignment.mod2.list2.title': '故障点干预',
    'alignment.mod2.list2.desc': '直接向逻辑流注入人工修正，无需重启进程。',
    'alignment.mod2.list3.title': '强化微调',
    'alignment.mod2.list3.desc': '每一次人工干预都会反馈到我们的对齐层，以防止未来再次出错。',
    'alignment.mockup.thread': '线程: COT_09X',
    'alignment.mockup.step1': '// 步骤 1: 查询Q4指标数据库',
    'alignment.mockup.step1.res': '结果: 潜在变量 [A] 与 [B] 之间存在高度相关性。',
    'alignment.mockup.step2.err': '!! 关键异常: 置信度分数 0.42',
    'alignment.mockup.step2.reason': '推理: 财务报表脚注中的归属不明确。',
    'alignment.mockup.step2.btn': '需要人工干预',
    'alignment.mockup.step3': '// 步骤 3: 综合 (等待用户干预...)',
    'pricing.title1': '选择您的',
    'pricing.title2': '项目方案',
    'pricing.desc': '为个人开发者与企业团队打造。以工业级可靠性与手术刀般的精准度，扩展您的基础设施。',
    'pricing.tab.individual': '个人用户',
    'pricing.tab.enterprise': '团队与企业',
    'pricing.free.badge': '方案 01',
    'pricing.free.title': '免费方案',
    'pricing.free.price': '¥0',
    'pricing.free.period': '/永久免费',
    'pricing.free.feat1': '每月 500 算力点',
    'pricing.free.feat2': '5 个活跃节点',
    'pricing.free.feat3': '基础 LLM 模型',
    'pricing.free.feat4': '不支持自带密钥',
    'pricing.free.btn': '当前方案',
    'pricing.pro.badge': '方案 02',
    'pricing.pro.title': '付费方案',
    'pricing.pro.popular': '最受欢迎',
    'pricing.pro.price': '¥20',
    'pricing.pro.period': '按Token计费',
    'pricing.pro.limit': '限定API范围内',
    'pricing.pro.feat1': '算力点永不过期',
    'pricing.pro.feat2': '高级逻辑模型',
    'pricing.pro.feat3': '自带密钥',
    'pricing.pro.feat4': '无限节点',
    'pricing.pro.btn': '立即开始',
    'pricing.ent.saas.badge': '标准部署方式',
    'pricing.ent.saas.title': 'SaaS 云端专业版',
    'pricing.ent.saas.price': '¥299',
    'pricing.ent.saas.period': '/ 月',
    'pricing.ent.saas.desc': '适用于中小机构。开箱即用的工作流平台与标准模板库，按席位/月订阅。',
    'pricing.ent.saas.feat1': '最高支持 10 个团队席位',
    'pricing.ent.saas.feat2': '50,000 计算积分',
    'pricing.ent.saas.feat3': '共享 GPU 集群',
    'pricing.ent.saas.btn': '部署实例',
    'pricing.ent.private.badge': '本地化 / 私有云部署',
    'pricing.ent.private.title': '企业私有化版',
    'pricing.ent.private.rec': '官方推荐',
    'pricing.ent.private.price': '定制',
    'pricing.ent.private.period': '咨询销售',
    'pricing.ent.private.desc': '针对极高数据隐私要求的国有企业与大型高校。支持本地化部署与开源私有模型搭载。',
    'pricing.ent.private.feat1': '物理隔离环境部署',
    'pricing.ent.private.feat2': '符合国家级模型规范',
    'pricing.ent.private.feat3': '自带密钥 (BYOK) 支持',
    'pricing.ent.private.feat4': '独占计算基础设施',
    'pricing.ent.private.btn': '联系销售',
    'pricing.ent.sdk.badge': '混合生态系统',
    'pricing.ent.sdk.title': '平台 SDK',
    'pricing.ent.sdk.price': '按量',
    'pricing.ent.sdk.period': '付费',
    'pricing.ent.sdk.desc': '直接基于 IntelliFlow 协议构建，通过原生 API 访问实现弹性伸缩。',
    'pricing.ent.sdk.feat1': '直连 API 端点',
    'pricing.ent.sdk.feat2': '全球边缘低延迟',
    'pricing.ent.sdk.feat3': '支持自定义中间件',
    'pricing.ent.sdk.btn': '查阅 SDK 文档',
    'pricing.credit.badge': '智能算力分配',
    'pricing.credit.title1': '算力引擎的无缝封装:',
    'pricing.credit.title2': '算力无感 (Frictionless Compute)',
    'pricing.credit.desc': '您无需关心复杂的底层 API Key 管理。IntelliFlow 统一集采头部大模型的 Token 算力，并转化为高价值的自动化审核服务。您只需通过消耗“执行点数（Credits）”即可按需运行工作流，极大降低了非技术人员的使用门槛。',
    'pricing.credit.feat1.title': '零延迟切换',
    'pricing.credit.feat1.desc': '根据实时可用性，在 H100 和 A100 集群之间自动迁移任务。',
    'pricing.credit.feat2.title': '预测性计费',
    'pricing.credit.feat2.desc': '精准了解每个工作流消耗的算力，精确到毫秒级。',
    'pricing.credit.img.label': '实时算力反馈: 102.4 TFLOPS',
    'pricing.cta.title': '准备好升级您的基础设施了吗？',
    'pricing.cta.desc': '加入全球顶尖团队，将 IntelliFlow 应用于关键任务运营。',
    'pricing.cta.btn1': '开始专业版试用',
    'pricing.cta.btn2': '与架构师进行交流',
    'pricing.trusted': '深受顶级学府与创新者信赖',
    'vision.mission.badge': '使命协议 01',
    'vision.mission.title1': '跨越',
    'vision.mission.title2': '数字鸿沟',
    'vision.mission.desc': '我们的使命：消除 AI 技术在严肃业务场景中的信任鸿沟，让完全不懂编程的行政与教务人员也能轻松指挥大模型，实现新一代人工智能信息技术的社会化普惠。',
    'vision.mission.feat1.title': '零代码自主性',
    'vision.mission.feat1.desc': '将人类意图转化为高精度的工业逻辑，无需编写任何传统代码。',
    'vision.mission.feat2.title': '神经民主化',
    'vision.mission.feat2.desc': '消除创新的门槛，为 LLM 编排提供直观的指令界面。',
    'vision.roadmap.title': '发展路线图',
    'vision.roadmap.subtitle': '持续迭代与规模化扩展',
    'vision.roadmap.q3q4.badge': '活跃阶段 (短期)',
    'vision.roadmap.q3q4.title': '垂直场景卓越化',
    'vision.roadmap.q3q4.desc1': '致力于在各类规则繁复、容错率极低的垂直业务场景中跑通跑透，沉淀企业级标准审核工作流。我们的当前重点是推出',
    'vision.roadmap.q3q4.desc2': '“通用资质与合规审查自动化协议”',
    'vision.roadmap.q3q4.desc3': '——一个能够泛化管理海量非结构化数据验证、合规性检查和业务发放的端到端智能工作流。我们将依托异构算子调度引擎，彻底打通从文档解析到结构化洞察的最后一公里，全面赋能政企与教育等多元化场景。',
    'vision.roadmap.q3q4.tag1': '政企与教育',
    'vision.roadmap.q3q4.tag2': '自动化审核',
    'vision.roadmap.q3q4.tag3': '合规性',
    'vision.roadmap.r1.title': '原生视觉 MLLMs',
    'vision.roadmap.r1.desc': '深度接入原生多模态视觉大模型，实现对任意复杂公章、手写体扫描件的零样本精准提取。',
    'vision.roadmap.r1.target': '目标：2025 R1',
    'vision.roadmap.r2.title': 'Agent 模板市场',
    'vision.roadmap.r2.desc': '构建“非结构化数据处理 Agent 模板交易市场”，供全球社区使用。',
    'vision.roadmap.r2.target': '目标：2025 R2',
    'vision.roadmap.team.title': '为精准而生',
    'vision.roadmap.team.desc': '我们的团队由来自数据分析、人工智能和 vibe coding 领域的高精度专家组成。',
    'vision.eco.title1': '两个世界，',
    'vision.eco.title2': '一个生态。',
    'vision.eco.desc': '在您的私有组织中安全协作，或在全球极客广场探索开源工作流模板。',
    'vision.eco.private.title': '私有组织工作区',
    'vision.eco.private.feat1': '基于域名的自动聚合',
    'vision.eco.private.feat2': '一键式工作流克隆',
    'vision.eco.private.feat3': '黑盒逻辑保护',
    'vision.eco.public.title': '公共极客动态',
    'vision.eco.public.user1.role': '精英贡献者',
    'vision.eco.public.user1.action': '刚刚发布了新的 \'Neural-Sync\' 工作流，用于实时数据摄取。',
    'vision.eco.public.user1.code1': '[exec] sync_neural_link --secure --v=high',
    'vision.eco.public.user1.code2': '> 正在聚合来自 :0812 的流',
    'vision.eco.public.user1.code3': '> 状态: 活跃',
    'vision.eco.public.user2.role': '贡献者',
    'vision.eco.public.link1': '全球工作流展示',
    'vision.eco.public.link2': '通过分享赚取算力点数奖励',
    'vision.eco.cta.btn': '探索社区',
    'vision.eco.cta.desc': '加入 12,000+ 名共同构建未来的工程师',
    'vision.quote.text1': '“我们不是在开发取代人类的工具，我们是在构建',
    'vision.quote.text2': '释放',
    'vision.quote.text3': '人类潜能的基础设施。”',
    'vision.quote.author': 'IntelliFlow 协作体',
    'footer.desc': '面向现代 AI 工作流的工业级编排引擎。',
    'footer.product': '产品',
    'footer.features': '特性',
    'footer.integrations': '集成',
    'footer.pricing': '定价',
    'footer.changelog': '更新日志',
    'footer.resources': '资源',
    'footer.docs': '官方文档',
    'footer.api': 'API 参考',
    'footer.community': '开发者社区',
    'footer.blog': '博客',
    'footer.company': '公司',
    'footer.about': '关于我们',
    'footer.careers': '加入我们',
    'footer.privacy': '隐私政策',
    'footer.terms': '服务条款',
    'footer.copyright': 'IntelliFlow 系统。为精准而生。',
  },
  en: {
    'nav.workflow': 'Workflow Engine',
    'nav.features': 'Core Features',
    'nav.architecture': 'Architecture',
    'nav.capabilities': 'Capabilities',
    'nav.alignment': 'Alignment',
    'nav.vision': 'Vision',
    'nav.pricing': 'Pricing',
    'nav.login': 'Sign In',
    'nav.start': 'Get Started',
    'hero.badge': 'Infrastructure 2.0 is now available',
    'hero.title': 'IntelliFlow: Built for Document Data Processing & Workflow Automation',
    'hero.desc': 'Industrial-grade infrastructure that makes complex automated DAG pipelines accessible.',
    'hero.start': 'Start Building',
    'hero.docs': 'Read Docs',
    'hero.node1': 'Excel Reader',
    'hero.node2': 'AI Model Engine',
    'hero.node3': 'WebHook Trigger',
    'features.dag.title': 'No-Code DAG Editor',
    'features.dag.desc': 'Drag-and-drop interface supporting seamless connection of thousands of logic nodes with real-time data preview.',
    'features.latency.title': 'Millisecond Latency',
    'features.latency.desc': 'Execution kernel designed for high-concurrency industrial scenarios, ensuring pipelines run at lightning speed on the edge.',
    'features.encryption.title': 'End-to-End Encryption',
    'features.encryption.desc': 'All sensitive data is processed in local and cloud encrypted environments, leaving no trace.',
    'features.integration.title': 'Deep Model Integration',
    'features.integration.desc': 'Native support for privately deployed industry-grade LLMs.',
    'features.telemetry.title': 'Real-Time Telemetry',
    'features.telemetry.desc': 'Precise monitoring of resource usage for every node and execution link analysis.',
    'flow.node1': 'Data Ingestion',
    'flow.node2': 'LLM Processing',
    'flow.node3': 'Result Generation',
    'flow.title': 'Visual DAG Orchestration',
    'flow.desc': 'Design complex workflows through an intuitive drag-and-drop interface. Seamlessly connect heterogeneous models and data sources.',
    'safety.core.title': 'Industrial-Grade Security Core',
    'safety.core.desc': 'Our kernel-level interception mechanism prevents LLMs from executing dangerous commands or violating company compliance policies before prompts reach the API.',
    'safety.redteam.title': 'Automated Red Teaming',
    'safety.redteam.desc': 'Continuous adversarial testing identifies vulnerabilities in specific model implementations before deployment.',
    'safety.reliability.title': 'Operational Reliability',
    'safety.compliance.title': 'Compliance Ready',
    'visual.label': 'Industrial Core',
    'visual.title1': 'Built for Complexity',
    'visual.title2': 'Without Being Bogged Down by It',
    'visual.desc': 'Before IntelliFlow, building cross-system data flows meant endless code debugging. Now, we abstract it into intuitive visual atomic nodes, allowing non-technical personnel to participate in building enterprise-grade infrastructure.',
    'visual.feature1.title': 'Elastic Scaling Architecture',
    'visual.feature1.desc': 'Supports automatic smooth scaling from single tasks to cluster levels.',
    'visual.feature2.title': 'Version Rollback System',
    'visual.feature2.desc': 'Complete Git-style workflow version management, restore to any historical state at any time.',
    'capabilities.badge': 'Core Capabilities 2.0',
    'capabilities.title1': 'Engineered',
    'capabilities.title2': 'Industrial-Grade',
    'capabilities.title3': 'Intelligence.',
    'capabilities.desc': 'Experience next-generation process automation. Our three-tier architecture combines reverse engineering with heterogeneous execution for surgical precision.',
    'capabilities.mod1.label': 'Module 01 // Intelligent Analysis',
    'capabilities.mod1.title': 'Few-Shot Reverse Engineering',
    'capabilities.mod1.desc1': 'Say goodbye to tedious hardcoding and exhaustive rules. IntelliFlow pioneers a native ',
    'capabilities.mod1.desc2': '"Master-Apprentice Mode"',
    'capabilities.mod1.desc3': '. Users only need to provide a triplet of "raw file + prompt intent + target result", and the underlying algorithm can instantly "comprehend", reverse-engineer intermediate reasoning steps like data extraction and level determination, and generate a visual Directed Acyclic Graph (DAG) workflow with one click.',
    'capabilities.mod1.box.title': 'Master-Apprentice Logic',
    'capabilities.mod1.box.desc': 'The "Master" AI observes expert interactions in real-time to extract high-dimensional logic patterns, while the "Apprentice" script engine synchronously generates optimized execution paths.',
    'capabilities.mod1.list1': 'Zero-latency pattern recognition',
    'capabilities.mod1.list2': 'Automatic filtering of user behavior noise',
    'capabilities.mod1.stat.label': 'Mapping Status',
    'capabilities.mod1.stat.value': '98.4% Accuracy',
    'capabilities.mod2.label': 'Module 02 // Efficient Execution',
    'capabilities.mod2.title': 'Heterogeneous Node Dual-Mode Drive',
    'capabilities.mod2.desc1': 'Why use a sledgehammer to crack a nut? We deeply integrate traditional deterministic algorithms (like regex matching, Python scripts) with non-deterministic AI semantic understanding. In IntelliFlow, LLMs no longer do everything, but are only responsible for the core ',
    'capabilities.mod2.desc2': 'logical reasoning (about 45%)',
    'capabilities.mod2.desc3': ', leaving the remaining ',
    'capabilities.mod2.desc4': '55% of data cleaning tasks',
    'capabilities.mod2.desc5': ' to low-cost local operators, achieving ultimate optimization of computing power and accuracy.',
    'capabilities.mod2.stat1.label': 'Cognitive AI',
    'capabilities.mod2.stat1.desc': 'Handles edge cases and dynamic decision gating.',
    'capabilities.mod2.stat2.label': 'Local Scripts',
    'capabilities.mod2.stat2.desc': 'High-speed, low-resource binary execution.',
    'capabilities.mod2.quote': '"By offloading repetitive tasks to optimized local scripts, we reduced server overhead by 64% while maintaining AI flexibility."',
    'capabilities.mod2.img.label1': 'Active Hybrid Mode',
    'capabilities.mod2.img.label2': 'Node: 0X-F42',
    'capabilities.mod3.label': 'Module 03 // Scale Expansion',
    'capabilities.mod3.title': 'Massive Concurrency & Automated Routing',
    'capabilities.mod3.desc1': 'Designed for enterprise-grade throughput. Whether it\'s hundreds of scholarship proof PDFs in various formats or complex business invoices, the automated batch center provides high-speed concurrent execution and queue monitoring. Combined with a ',
    'capabilities.mod3.desc2': 'dynamic routing distribution mechanism',
    'capabilities.mod3.desc3': ', it intelligently schedules the most suitable closed-source LLM API for the current node.',
    'capabilities.mod3.chart.label1': 'Global Flow Rate',
    'capabilities.mod3.chart.label2': 'Real-time Metrics',
    'capabilities.cta.title': 'Ready to optimize your processes?',
    'capabilities.cta.desc': 'Deploy in less than 15 minutes using our pre-built industrial connectors. Zero downtime integration guaranteed.',
    'capabilities.cta.btn': 'Request Prototype Trial',
    'capabilities.cta.sla.label': 'Uptime SLA',
    'capabilities.cta.sla.desc': 'Redundant routing across 14 global regions ensures your automation never goes offline.',
    'alignment.badge': 'System Integrity Protocol',
    'alignment.title1': 'Taming',
    'alignment.title2': 'LLMs',
    'alignment.desc': 'LLMs no longer dictate your output. IntelliFlow introduces a multi-layer industrial-grade foundation designed to intercept hallucinations and align non-deterministic reasoning with business reality.',
    'alignment.btn': 'View Safety Standards',
    'alignment.stat1.label': 'TOKEN_ENTROPY',
    'alignment.stat2.label': 'ALIGNMENT_SCORE',
    'alignment.mod1.label': 'Module 01 // Hallucination Suppression',
    'alignment.mod1.title': 'Conquer Attention Loss, Suppress Hallucinations at the Physical Level',
    'alignment.mod1.desc': 'When a model swallows massive amounts of text and images at once, it is highly prone to "Lost in the Middle" attention loss and data fabrication. IntelliFlow adopts a divide-and-conquer strategy, forcibly decoupling global tasks into atomic node tasks via DAG workflows. Each node only obtains the minimum necessary context. "AI handles fuzzy cognition, code handles precise execution", converging the model\'s action space to the extreme, fundamentally eliminating business hallucinations.',
    'alignment.mod1.card1.title': 'Node Isolation',
    'alignment.mod1.card1.desc': 'Each logical step is processed in a sterile computing environment, stripping away irrelevant context noise.',
    'alignment.mod1.card2.title': 'Cross-Validation',
    'alignment.mod1.card2.desc': 'Outputs are automatically verified against internal knowledge graphs, flagging inconsistencies in real-time.',
    'alignment.mod1.card3.title': 'Confidence Gate',
    'alignment.mod1.card3.desc': 'Tokens below a specific entropy threshold are locked and redirected to recursive sampling or human audit.',
    'alignment.mod2.label': 'Module 02 // Human-in-the-Loop',
    'alignment.mod2.title': 'Visualized Chain of Thought & Targeted Intervention',
    'alignment.mod2.desc': 'We externalize the LLM\'s hidden "Chain of Thought" into an interactive node connection graph on the frontend. If the AI misjudges at a micro-node (like competition grading), humans can directly intercept and reconstruct at that node. By setting a "Confidence Gate", low-confidence tasks are automatically pooled for manual review, truly realizing the zero-error system baseline of "AI does the heavy lifting, humans hit the brakes".',
    'alignment.mod2.list1.title': 'Visual Transparency',
    'alignment.mod2.list1.desc': 'Real-time stream of the model\'s inner monologue, formatted for industrial auditing.',
    'alignment.mod2.list2.title': 'Fault Point Intervention',
    'alignment.mod2.list2.desc': 'Inject human corrections directly into the logic flow without restarting the process.',
    'alignment.mod2.list3.title': 'Reinforcement Fine-Tuning',
    'alignment.mod2.list3.desc': 'Every human intervention feeds back into our alignment layer to prevent future recurrences.',
    'alignment.mockup.thread': 'Thread: COT_09X',
    'alignment.mockup.step1': '// Step 1: Query Q4 metrics database',
    'alignment.mockup.step1.res': 'Result: High correlation exists between latent variables [A] and [B].',
    'alignment.mockup.step2.err': '!! Critical Anomaly: Confidence score 0.42',
    'alignment.mockup.step2.reason': 'Reasoning: Ambiguous attribution in financial statement footnotes.',
    'alignment.mockup.step2.btn': 'Human Intervention Required',
    'alignment.mockup.step3': '// Step 3: Synthesis (Waiting for user intervention...)',
    'pricing.title1': 'Choose Your',
    'pricing.title2': 'Project Plan',
    'pricing.desc': 'Built for individual developers and enterprise teams. Scale your infrastructure with industrial-grade reliability and surgical precision.',
    'pricing.tab.individual': 'Individuals',
    'pricing.tab.enterprise': 'Teams & Enterprise',
    'pricing.free.badge': 'Plan 01',
    'pricing.free.title': 'Free Plan',
    'pricing.free.price': '$0',
    'pricing.free.period': '/Forever Free',
    'pricing.free.feat1': '500 Compute Credits / Month',
    'pricing.free.feat2': '5 Active Nodes',
    'pricing.free.feat3': 'Basic LLM Models',
    'pricing.free.feat4': 'BYOK Not Supported',
    'pricing.free.btn': 'Current Plan',
    'pricing.pro.badge': 'Plan 02',
    'pricing.pro.title': 'Pro Plan',
    'pricing.pro.popular': 'Most Popular',
    'pricing.pro.price': '$20',
    'pricing.pro.period': 'Pay per Token',
    'pricing.pro.limit': 'Within API Limits',
    'pricing.pro.feat1': 'Compute Credits Never Expire',
    'pricing.pro.feat2': 'Advanced Logic Models',
    'pricing.pro.feat3': 'Bring Your Own Key (BYOK)',
    'pricing.pro.feat4': 'Unlimited Nodes',
    'pricing.pro.btn': 'Start Now',
    'pricing.ent.saas.badge': 'Standard Deployment',
    'pricing.ent.saas.title': 'SaaS Cloud Pro',
    'pricing.ent.saas.price': '$299',
    'pricing.ent.saas.period': '/ Month',
    'pricing.ent.saas.desc': 'Suitable for SMEs. Out-of-the-box workflow platform and standard template library, billed per seat/month.',
    'pricing.ent.saas.feat1': 'Up to 10 Team Seats',
    'pricing.ent.saas.feat2': '50,000 Compute Credits',
    'pricing.ent.saas.feat3': 'Shared GPU Cluster',
    'pricing.ent.saas.btn': 'Deploy Instance',
    'pricing.ent.private.badge': 'Local / Private Cloud',
    'pricing.ent.private.title': 'Enterprise Private',
    'pricing.ent.private.rec': 'Recommended',
    'pricing.ent.private.price': 'Custom',
    'pricing.ent.private.period': 'Consult Sales',
    'pricing.ent.private.desc': 'For SOEs and large universities with extreme data privacy requirements. Supports local deployment and open-source private models.',
    'pricing.ent.private.feat1': 'Physically Isolated Environment',
    'pricing.ent.private.feat2': 'Compliant with National Model Standards',
    'pricing.ent.private.feat3': 'Bring Your Own Key (BYOK) Support',
    'pricing.ent.private.feat4': 'Exclusive Compute Infrastructure',
    'pricing.ent.private.btn': 'Contact Sales',
    'pricing.ent.sdk.badge': 'Hybrid Ecosystem',
    'pricing.ent.sdk.title': 'Platform SDK',
    'pricing.ent.sdk.price': 'Pay-as',
    'pricing.ent.sdk.period': '-you-go',
    'pricing.ent.sdk.desc': 'Build directly on the IntelliFlow protocol, achieving elastic scaling via native API access.',
    'pricing.ent.sdk.feat1': 'Direct API Endpoints',
    'pricing.ent.sdk.feat2': 'Global Edge Low Latency',
    'pricing.ent.sdk.feat3': 'Custom Middleware Support',
    'pricing.ent.sdk.btn': 'View SDK Docs',
    'pricing.credit.badge': 'Intelligent Compute Allocation',
    'pricing.credit.title1': 'Seamless Encapsulation of Compute Engine:',
    'pricing.credit.title2': 'Frictionless Compute',
    'pricing.credit.desc': 'No need to worry about complex underlying API Key management. IntelliFlow centrally procures Token compute from top LLMs and converts it into high-value automated review services. You only need to consume "Credits" to run workflows on demand, greatly lowering the barrier to entry for non-technical users.',
    'pricing.credit.feat1.title': 'Zero-Latency Switching',
    'pricing.credit.feat1.desc': 'Automatically migrate tasks between H100 and A100 clusters based on real-time availability.',
    'pricing.credit.feat2.title': 'Predictive Billing',
    'pricing.credit.feat2.desc': 'Accurately understand the compute consumed by each workflow, down to the millisecond.',
    'pricing.credit.img.label': 'Real-time Compute Feedback: 102.4 TFLOPS',
    'pricing.cta.title': 'Ready to upgrade your infrastructure?',
    'pricing.cta.desc': 'Join top global teams and apply IntelliFlow to mission-critical operations.',
    'pricing.cta.btn1': 'Start Pro Trial',
    'pricing.cta.btn2': 'Talk to an Architect',
    'pricing.trusted': 'Trusted by Top Institutions & Innovators',
    'vision.mission.badge': 'Mission Protocol 01',
    'vision.mission.title1': 'Bridging the',
    'vision.mission.title2': 'Digital Divide',
    'vision.mission.desc': 'Our mission: Eliminate the trust gap of AI technology in serious business scenarios, allowing administrative and educational staff with zero programming knowledge to easily command large models, realizing the social democratization of next-generation AI information technology.',
    'vision.mission.feat1.title': 'Zero-Code Autonomy',
    'vision.mission.feat1.desc': 'Translate human intent into high-precision industrial logic without writing any traditional code.',
    'vision.mission.feat2.title': 'Neural Democratization',
    'vision.mission.feat2.desc': 'Eliminate barriers to innovation by providing an intuitive instruction interface for LLM orchestration.',
    'vision.roadmap.title': 'Development Roadmap',
    'vision.roadmap.subtitle': 'Continuous Iteration & Scalable Expansion',
    'vision.roadmap.q3q4.badge': 'Active Phase (Short Term)',
    'vision.roadmap.q3q4.title': 'Vertical Scenario Excellence',
    'vision.roadmap.q3q4.desc1': 'Dedicated to running through and mastering various vertical business scenarios with complex rules and extremely low fault tolerance, precipitating enterprise-grade standard review workflows. Our current focus is launching the ',
    'vision.roadmap.q3q4.desc2': '"Universal Qualification and Compliance Review Automation Protocol"',
    'vision.roadmap.q3q4.desc3': ' — an end-to-end intelligent workflow capable of generalizing the management of massive unstructured data verification, compliance checks, and business issuance. Relying on the heterogeneous operator scheduling engine, we will thoroughly bridge the last mile from document parsing to structured insights, comprehensively empowering diverse scenarios such as government, enterprise, and education.',
    'vision.roadmap.q3q4.tag1': 'Gov & Edu',
    'vision.roadmap.q3q4.tag2': 'Auto Review',
    'vision.roadmap.q3q4.tag3': 'Compliance',
    'vision.roadmap.r1.title': 'Native Visual MLLMs',
    'vision.roadmap.r1.desc': 'Deep integration with native multimodal visual large models to achieve zero-shot accurate extraction of arbitrarily complex official seals and handwritten scanned documents.',
    'vision.roadmap.r1.target': 'Target: 2025 R1',
    'vision.roadmap.r2.title': 'Agent Template Market',
    'vision.roadmap.r2.desc': 'Build an "Unstructured Data Processing Agent Template Trading Market" for the global community.',
    'vision.roadmap.r2.target': 'Target: 2025 R2',
    'vision.roadmap.team.title': 'Built for Precision',
    'vision.roadmap.team.desc': 'Our team consists of high-precision experts from data analytics, artificial intelligence, and vibe coding.',
    'vision.eco.title1': 'Two Worlds,',
    'vision.eco.title2': 'One Ecosystem.',
    'vision.eco.desc': 'Collaborate securely in your private organization, or explore open-source workflow templates in the global geek plaza.',
    'vision.eco.private.title': 'Private Org Workspace',
    'vision.eco.private.feat1': 'Domain-based Auto Aggregation',
    'vision.eco.private.feat2': 'One-Click Workflow Cloning',
    'vision.eco.private.feat3': 'Black-Box Logic Protection',
    'vision.eco.public.title': 'Public Geek Feed',
    'vision.eco.public.user1.role': 'Elite Contributor',
    'vision.eco.public.user1.action': 'Just published a new \'Neural-Sync\' workflow for real-time data ingestion.',
    'vision.eco.public.user1.code1': '[exec] sync_neural_link --secure --v=high',
    'vision.eco.public.user1.code2': '> Aggregating stream from :0812',
    'vision.eco.public.user1.code3': '> Status: Active',
    'vision.eco.public.user2.role': 'Contributor',
    'vision.eco.public.link1': 'Global Workflow Showcase',
    'vision.eco.public.link2': 'Earn Compute Credits by Sharing',
    'vision.eco.cta.btn': 'Explore Community',
    'vision.eco.cta.desc': 'Join 12,000+ engineers building the future together',
    'vision.quote.text1': '"We are not building tools to replace humans, we are building infrastructure to ',
    'vision.quote.text2': 'unleash',
    'vision.quote.text3': ' human potential."',
    'vision.quote.author': 'IntelliFlow Collective',
    'footer.desc': 'Industrial-grade orchestration engine for modern AI workflows.',
    'footer.product': 'Product',
    'footer.features': 'Features',
    'footer.integrations': 'Integrations',
    'footer.pricing': 'Pricing',
    'footer.changelog': 'Changelog',
    'footer.resources': 'Resources',
    'footer.docs': 'Documentation',
    'footer.api': 'API Reference',
    'footer.community': 'Community',
    'footer.blog': 'Blog',
    'footer.company': 'Company',
    'footer.about': 'About Us',
    'footer.careers': 'Careers',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.copyright': 'IntelliFlow System. Built for precision.',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('zh');

  useEffect(() => {
    document.documentElement.lang = language === 'zh' ? 'zh-CN' : 'en';
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
